# Basic colors
foreground              #e2e2e9
background              #111318
selection_foreground    #dbe2f9
selection_background    #3f4759

# Cursor colors
cursor                  #adc6ff
cursor_text_color       #102f60

# URL underline color when hovering with mouse
url_color               #debcdf

# Kitty window border colors
active_border_color     #adc6ff
inactive_border_color   #44474f
bell_border_color       #ffb4ab

# OS Window titlebar colors
wayland_titlebar_color  system
macos_titlebar_color    system

# Tab bar colors
active_tab_foreground   #d8e2ff
active_tab_background   #2b4678
inactive_tab_foreground #c4c6d0
inactive_tab_background #1e1f25
tab_bar_background      #111318

# Colors for marks
mark1_foreground #102f60
mark1_background #adc6ff
mark2_foreground #293041
mark2_background #bfc6dc
mark3_foreground #402843
mark3_background #debcdf

# The 16 terminal colors
# black
color0 #44474f
color8 #8e9099

# red
color1 #ffb4ab
color9 #93000a

# green
color2  #adc6ff
color10 #d8e2ff

# yellow
color3  #debcdf
color11 #fbd7fc

# blue
color4  #bfc6dc
color12 #dbe2f9

# magenta
color5  #2b4678
color13 #445e91

# cyan
color6  #3f4759
color14 #583e5b

# white
color7  #c4c6d0
color15 #e2e2e9
